name: eco_coin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  animations: ^2.0.11
  camera: ^0.11.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_image_compress: ^2.4.0
  google_fonts: ^6.3.1
  image: ^4.5.4
  permission_handler: ^11.3.1
  provider: ^6.1.5+1
  tflite_flutter: ^0.11.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "eco_coin_icon"
  ios: true
  image_path: "assets/images/ic_eco_coin.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/ic_eco_coin.png"
  windows:
    generate: true
    image_path: "assets/images/ic_eco_coin.png"
  macos:
    generate: true
    image_path: "assets/images/ic_eco_coin.png"

flutter:
  assets:
    - .env
    - assets/images/
    - assets/lottie/
    - assets/models/
  uses-material-design: true
  # Note: Add .env file to your project root every clone this project
