// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ3sCB6BocmVJkoQrP4TU9NNjFik3ZiBk',
    appId: '1:881744304659:web:38ee89c31c066f13bd3de6',
    messagingSenderId: '881744304659',
    projectId: 'eco-coin-444fd',
    authDomain: 'eco-coin-444fd.firebaseapp.com',
    storageBucket: 'eco-coin-444fd.firebasestorage.app',
    measurementId: 'G-XXPLNVZ4Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAksCOkhimk46KbutDzaYKpBxTTR87KeIM',
    appId: '1:881744304659:android:c0807f5626345189bd3de6',
    messagingSenderId: '881744304659',
    projectId: 'eco-coin-444fd',
    storageBucket: 'eco-coin-444fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp7rA93fgWLiOHW9ZFqg4syimVSm0diHA',
    appId: '1:881744304659:ios:09d459caa12fe465bd3de6',
    messagingSenderId: '881744304659',
    projectId: 'eco-coin-444fd',
    storageBucket: 'eco-coin-444fd.firebasestorage.app',
    iosBundleId: 'com.example.ecoCoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp7rA93fgWLiOHW9ZFqg4syimVSm0diHA',
    appId: '1:881744304659:ios:09d459caa12fe465bd3de6',
    messagingSenderId: '881744304659',
    projectId: 'eco-coin-444fd',
    storageBucket: 'eco-coin-444fd.firebasestorage.app',
    iosBundleId: 'com.example.ecoCoin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ3sCB6BocmVJkoQrP4TU9NNjFik3ZiBk',
    appId: '1:881744304659:web:7e59c1f1c92dd339bd3de6',
    messagingSenderId: '881744304659',
    projectId: 'eco-coin-444fd',
    authDomain: 'eco-coin-444fd.firebaseapp.com',
    storageBucket: 'eco-coin-444fd.firebasestorage.app',
    measurementId: 'G-4DSCLNFX8B',
  );
}
